baseURL = 'https://alexandre.wtf/'
languageCode = 'en-us'
title = 'Alexandre Ferreira - Data & AI Engineer'
theme = ['elderly']


[Params]
author = "Alexandre Ferreira"
description = "Alexandre Ferreira's personal website, blog and portfolio, showcasing his work and expertise in Data and AI engineering, also personal projects."

[Params.head]
og_image = "image/favicon/icon-64x64.png"

[Params.profile]
name = "Alexandre Ferreira"
role = "Data & AI Engineer"
avatar = "/images/avatar.png"

[Params.social]
github = "https://github.com/alexandresgf"
linkedin = "https://www.linkedin.com/in/alexandresgf"
twitter = "https://twitter.com/todiojisan"
